baseURL = '/'
languageCode = 'it-it'
title = 'CyberEagles - headquarter'

[minify]
  minifyOutput = true



[module]
[[module.imports]]
    path = 'github.com/yukuro/hugo-theme-shell'

  [Params]
  description = "team cybereagles"
  [Params.Terminal]
  scheme = "shell-ubuntu"

  userName = "cybereagles"
  pcName = "headquarter"
  workDir = "informazioni"
  profile = "who-we-are.txt"

  ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
  stdoutDelay = 0 # stdout speed : [description] , files in Params.Tree
  commandDelay = 50 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

  titleDelay = 0 # title speed : "title" in front matter
  contentDelay = 0 # content speed : content in .md file


  description = """
  Ciao, benvenuti nel quartier generale di CyberEagles!
  Siamo un gruppo di ragazzi appassionati di Cybersecurity!
  Scopri di più sulle nostre attività e progetti qui sotto.

   <p>* Nati per la sicurezza.</p> <p>* Felici possessori del <a target="_blank" href="https://pwnagotchi.ai/">Pwnagotchi</a>!</p><p>* Inside your kernel space: We Hack, You Sleep!</p> 
   Maggiori info: <a target="_blank" href="https://linktr.ee/cybereagles">LinkTree</a>
  
  """


  [Params.Tree]
  folderName = "componenti-del-Team"
  use = true
  componenti = "componenti"
  files = [ 
    ["Noemi De Martino - Leader Supremo", "https://linkedin.com/"],
    ["Victoria Braile - Canva Master", "https://linkedin.com/"],
    ["Cristian Bonaldi - Google Chrome addicted", "https://linkedin.com/"],
    ["Matteo Beltrami Marzolini - CTO Sala delle Torture", "https://linkedin.com/"],
    ["Flavio Scognamiglio - NPLS (Nato Per La Sicurezza)", "https://linkedin.com/"],
    ["Mattia Fossati - Pro Builder", "https://linkedin.com/"],
    ["Antonio Spallone - Chilling expert", "https://linkedin.com/"],
    ["Sara Ortiz - Traveling Cyber Security Specialist", "https://linkedin.com/"],
    ["Paolo Romeo - Legal department", "https://linkedin.com/"],
    ["Matteo Zerbi - Dynamic Team Member", "https://linkedin.com/"],
  ]

